language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t dichtrich/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dichtrich/react-test npm test -- --coverage

after_success:
  - docker build -t dichtrich/complex-client ./client
  - docker build -t dichtrich/complex-nginx ./nginx
  - docker build -t dichtrich/complex-server ./server
  - docker build -t dichtrich/complex-worker ./worker
  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push dichtrich/complex-client
  - docker push dichtrich/complex-nginx
  - docker push dichtrich/complex-server
  - docker push dichtrich/complex-worker 